### ISSUE TITLE
Looks?

### ISSUE THREAD

**Issue by JustSteveKing** [rtablada/admin-bulma#2]
Any chance you could pull in a screenshot of this in action so we know what this looks like?

**Comment by c10ce** [comment]
Hiya @JustSteveKing,

I took screenshots of the examples from the repo:

![bulma-admin-bar](https://user-images.githubusercontent.com/1347389/30988243-b7ecf5fc-a467-11e7-859a-3298e58a6c23.png)

![bulma-admin-bar-collapsed](https://user-images.githubusercontent.com/1347389/30988242-b7e8be74-a467-11e7-83ad-d41cee2adc84.png)

Cheers!
